### ISSUE TITLE
onRowSelection tree rerenders

### ISSUE THREAD

**Issue by suneethar** [cheton/react-infinite-tree#3]
Hi,

I was facing an issue where onRowSelection tree is rerendered , no expand or collapse I have just selected the node.

Thanks and Regards,
Suneetha

**Comment by cheton** [comment]
Calling "selectNode" will trigger an update to clusterize to re-render the whole thing:

https://github.com/cheton/infinite-tree/blob/master/src/infinite-tree.js#L1116

``` js
selectNode(node = null, options) {
    :    :    :
    // Updates list with new data
    this.update();
}
```

https://github.com/cheton/infinite-tree/blob/master/src/infinite-tree.js#L1178

``` js
update() {
    // Emit a "contentWillUpdate" event
    this.emit('contentWillUpdate');

    // Update the list with new data
    this.clusterize.update(this.rows);

    // Emit a "contentWillUpdate" event
    this.emit('contentDidUpdate');
}
```

By now it's a kind of limitation because the [infinite-tree](https://github.com/cheton/infinite-tree) library uses [Clusterize.js](https://clusterize.js.org/) for rendering, I may need to rewrite this part in the future.
